version: "3.9"
services:
  webapp:
    container_name: sql-inj-webapp
    build: ./docker/franken
    ports:
      - "8000:80"
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    tty: true
    networks:
      - network
  db:
    container_name: sql-inj-db
    image: mariadb:10.5.8
    restart: always
    volumes:
      - ./var/db-data:/var/lib/mysql
      #- ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: app_db
      TZ: Europe/Paris
    networks:
      - network
  #PHP My Admin
#  phpmyadmin:
#    container_name: sql-inj-pma
#    image: phpmyadmin
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - "8081:80"
#    environment:
#      PMA_HOST: db
#    networks:
#      - network
volumes:
  caddy_data:
  caddy_config:
networks:
  network:
